# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: gluon
  joint_model_group_pose: home_pose
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 10
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - axis_joint_1
    - axis_joint_2
    - axis_joint_3
    - axis_joint_4
    - axis_joint_5
    - axis_joint_6
  sim_control_mode: 0  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
gluon_controller:
    action_ns: follow_joint_trajectory
    default: True
    type: position_controllers/JointTrajectoryController
    joints:
      - axis_joint_1
      - axis_joint_2
      - axis_joint_3
      - axis_joint_4
      - axis_joint_5
      - axis_joint_6
